// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOVRwyGQ1Tl2qkTi5gar9fNf8DIV6APqc',
    appId: '1:533339156031:web:2217eb9048f8434d33d28a',
    messagingSenderId: '533339156031',
    projectId: 'fashion-market-bcd24',
    authDomain: 'fashion-market-bcd24.firebaseapp.com',
    storageBucket: 'fashion-market-bcd24.appspot.com',
    measurementId: 'G-CBKHXZLQYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDggAK-4OwguTSORTXY1QSlZXpMdSeo6KA',
    appId: '1:533339156031:android:f17e69641ba6b7c133d28a',
    messagingSenderId: '533339156031',
    projectId: 'fashion-market-bcd24',
    storageBucket: 'fashion-market-bcd24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCzP8a5-xUAzvNyzN90Na0JpqH8lVcHTE',
    appId: '1:533339156031:ios:f9a8fc2af6a597c533d28a',
    messagingSenderId: '533339156031',
    projectId: 'fashion-market-bcd24',
    storageBucket: 'fashion-market-bcd24.appspot.com',
    iosBundleId: 'com.example.fashionMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCzP8a5-xUAzvNyzN90Na0JpqH8lVcHTE',
    appId: '1:533339156031:ios:f9a8fc2af6a597c533d28a',
    messagingSenderId: '533339156031',
    projectId: 'fashion-market-bcd24',
    storageBucket: 'fashion-market-bcd24.appspot.com',
    iosBundleId: 'com.example.fashionMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOVRwyGQ1Tl2qkTi5gar9fNf8DIV6APqc',
    appId: '1:533339156031:web:ef76584e13af974f33d28a',
    messagingSenderId: '533339156031',
    projectId: 'fashion-market-bcd24',
    authDomain: 'fashion-market-bcd24.firebaseapp.com',
    storageBucket: 'fashion-market-bcd24.appspot.com',
    measurementId: 'G-T5Y1722SXV',
  );
}
